baseURL = "https://cv.chalichen.cat/"
languageCode = "es-es"
title = "Curr√≠culum Vitae"

theme = "careercanvas"

[params]

  [params.pexels]
    enable = true

    [params.pexels.queries]
      hero = "software developer"